#!/usr/bin/env python3
"""Dump local data/tracker.db into D1-importable SQL (data only).

Usage (from repo root containing data/tracker.db):
  python3 cloudflare/scripts/export_sqlite_to_d1.py \\
      --db data/tracker.db \\
      --out cloudflare/scripts/d1_data.sql

Then apply remotely after migrations:
  cd cloudflare/worker
  npx wrangler d1 execute starship-tracker --remote --file=../scripts/d1_data.sql

Omits ll2_raw_json (large, regenerable from the next LL2 poll) to keep the
import small and under D1 statement limits.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path


TABLES = ("flights", "net_history", "articles", "signals", "meta")


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, (bytes, memoryview)):
        value = bytes(value).decode("utf-8", errors="replace")
    text = str(value).replace("'", "''")
    return f"'{text}'"


def dump_table(conn: sqlite3.Connection, table: str, out) -> int:
    cols = [r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()]
    if not cols:
        return 0
    # Drop bulky regenerable LL2 blobs from the migration dump.
    write_cols = [c for c in cols if c != "ll2_raw_json"]
    rows = conn.execute(
        f"SELECT {', '.join(write_cols)} FROM {table}"
    ).fetchall()
    if not rows:
        return 0
    out.write(f"-- {table}: {len(rows)} rows\n")
    col_list = ", ".join(write_cols)
    for row in rows:
        values = ", ".join(sql_literal(v) for v in row)
        out.write(f"INSERT OR REPLACE INTO {table} ({col_list}) VALUES ({values});\n")
    out.write("\n")
    return len(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--db",
        type=Path,
        default=Path("data/tracker.db"),
        help="Path to local SQLite tracker.db",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("cloudflare/scripts/d1_data.sql"),
        help="Output SQL path (gitignored)",
    )
    args = parser.parse_args()
    if not args.db.exists():
        raise SystemExit(f"Database not found: {args.db}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(args.db))
    counts: dict[str, int] = {}
    with args.out.open("w", encoding="utf-8") as out:
        out.write("-- Generated by export_sqlite_to_d1.py — data only, no DDL\n")
        out.write("PRAGMA foreign_keys = OFF;\n\n")
        for table in TABLES:
            counts[table] = dump_table(conn, table, out)
        out.write("PRAGMA foreign_keys = ON;\n")
    conn.close()
    print(json.dumps({"out": str(args.out), "counts": counts}, indent=2))


if __name__ == "__main__":
    main()
